// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prmxvxgayciizaxkuxgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybXh2eGdheWNpaXpheGt1eGduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxOTMyNTcsImV4cCI6MjA2MTc2OTI1N30.lxrMQ7xD2i-3b0WOGbshyYXS88QE7rTNCJiHdh7Zi5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);